$schema: https://azuremlschemas.azureedge.net/latest/managedOnlineDeployment.schema.json
name: blue
endpoint_name: WS-mbart-grammar-corrector-de
model:
  path: ../../mbart-german-grammar-corrector/
code_configuration:
  code: ../../mbart-german-grammar-corrector/onlinescoring/
  scoring_script: score.py
environment:
  conda_file: ../../mbart-german-grammar-corrector/environment/conda.yaml
  image: mcr.microsoft.com/azureml/openmpi4.1.0-ubuntu22.04:latest
instance_type: Standard_DS2_v2
instance_count: 1
