$schema: https://azuremlschemas.azureedge.net/latest/environment.schema.json
name: mbart-german-grammar-corrector--env
image: mcr.microsoft.com/azureml/openmpi4.1.0-ubuntu20.04:latest
conda_file: ../../mbart-german-grammar-corrector/environment/conda.yaml
